### ISSUE TITLE
While adding a new tasks, the checked tasks become unchecked

### ISSUE THREAD

**Issue by alphabug01** [Divyanshu2411/To-Do#1]
I added three tasks. I checked two tasks and added another task. While adding the task, all the checked tasks are reset to unchecked

**Comment by alphabug01** [comment]
The same is happening when deleting a task, this may be due to the renderList(). I believe it may need some changes.

**Comment by Divyanshu2411** [comment]
Indeed, it's because of the renderList(), i have emptied the list before adding it again, it's probably because of that

**Comment by alphabug01** [comment]
![Screenshot from 2020-08-31 13-48-11](https://user-images.githubusercontent.com/38398894/91702626-9ecbce80-eb96-11ea-9089-e024d25a5af4.png)
I tried to debug the js file. I found that the problem is not in the renderList. I thought it may be because of the task.done value (in the render list function) is reset to default false and was thinking way around to solve it but when I debugging I found that the checkToDo function is the problem. When clicked on the checkbox whether to check or uncheck, the function is not called and the value of tasks[index].done is not altered. Hence it is false all the time

**Comment by alphabug01** [comment]
I have forked the repository. I will make the pull request when I commit changes and we can close this issue.

**Comment by Divyanshu2411** [comment]
Thank you, yes you are right, i can see the issue now. I was thinking that it was due to a problem in renderList

**Comment by Divyanshu2411** [comment]
I have added a functionality of tasks being visually cut after they are done
