### ISSUE TITLE
How do i get fonts that look like handwritings on my webpage

### ISSUE THREAD

**Issue by Divyanshu2411** [Divyanshu2411/To-Do#3]

**Comment by alphabug01** [comment]
To add custom fonts, google fonts ([https://fonts.google.com/](URL)) or web fonts can be used. There are some handwritten fonts in _google fonts_ and to embed the font, the code is provided to copy into the `<head>` of the HTML file

**Comment by Divyanshu2411** [comment]
Thank you so much, this was really helpful!
